# Generated by Django 5.1 on 2024-08-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_genre_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Category',
        ),
    ]
